# Generated by Django 2.2.5 on 2019-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='remote_id',
            field=models.IntegerField(),
        ),
    ]
