# Generated by Django 2.2.5 on 2019-09-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190909_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='remote_id',
        ),
    ]
